### ISSUE TITLE
"No stream data exists for inferring a schema" when inferSchema is false

### ISSUE THREAD

**Issue by davidmessem** [maropu/spark-kinesis-sql-asl#2]
Hi

I tried to run the example code on my own stream.

      val kinesis = spark
         .readStream
         .format("kinesis")
         .option("streams", "my_stream")
         .option("endpointUrl", "kinesis.eu-west-1.amazonaws.com")
         .option("initialPositionInStream", "earliest")
         .option("format", "json")
         .option("inferSchema", "true")
         .load()

I got the "No stream data exists for inferring a schema" error, even though there has been data in the stream.

I then set "inferSchema" to "false", and got the same error.

**Comment by maropu** [comment]
Thanks for the report. I'll check.

**Comment by maropu** [comment]
In that case, you need to set a schema explicitly:
https://github.com/maropu/spark-kinesis-sql-asl#creating-a-kinesis-source-stream
For now, I'll close this ticket though, you feel free to open a new ticket if you have better idea to handle these cases. Thanks!

**Comment by davidmessem** [comment]
Thanks for the explanation!
